"""add_agent_is_example

Revision ID: a0b9b6215dcd
Revises: ad9da9216ac8
Create Date: 2026-06-30 12:52:24.770351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b9b6215dcd'
down_revision: Union[str, Sequence[str], None] = 'ad9da9216ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_example', sa.String(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_example')
    # ### end Alembic commands ###
